# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/boxwood-sector-436512-f3/test1/helloworld:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/boxwood-sector-436512-f3/test1/helloworld:latest']

images:
  - 'LOCATION-docker.pkg.dev/boxwood-sector-436512-f3/test1/helloworld:latest'

# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
